name: Daily Commit

on:
  schedule:
    - cron: "30 2 * * *"  # Runs daily at 02:30 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update File and Commit
        run: |
          echo "Last run: $(date)" >> daily_update.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add daily_update.txt
          git commit -m "Automated daily commit - $(date)"
          git push

      - name: 23f2004829@ds.study.iitm.ac.in  # Step with your email in its name
        run: echo "Email step executed"
